
services:
  # Нижний уровень: собирает метрики напрямую с объектов
  prom-worker:
    image: prom/prometheus:v3.1.0 # Используем актуальную версию v3.x
    container_name: prom-worker
    network_mode: host # Позволяет использовать честный localhost
    volumes:
      - ./prom-worker.yaml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
  #ports:
  #    - "9091:9090" # Доступен на хосте по порту 9091

  # Верхний уровень: забирает метрики из prom-worker
  prom-master:
    image: prom/prometheus:v3.1.0
    container_name: prom-master
    volumes:
      - ./prom-master.yaml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9092:9090" # Доступен на хосте по порту 9092
    depends_on:
      - prom-worker
    extra_hosts:
      - "host.docker.internal:host-gateway" # Гарантирует, что Мастер увидит Воркера через этот DNS

  grafana:
    image: grafana/grafana:11.5.2
    container_name: prom-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prom-master
    volumes:
      # Монтируем файл источника данных
      - ./grafana-provisioning/datasources/prometheus.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml:ro
      # Монтируем провайдер дашбордов
      - ./grafana-provisioning/dashboards/provider.yaml:/etc/grafana/provisioning/dashboards/provider.yaml:ro
      # Монтируем папку, где лежат сами JSON-файлы дашбордов
      - ./grafana-provisioning/dashboards:/var/lib/grafana/dashboards:ro
