{
 "title": "Мониторинг ядер CPU (Node Exporter)",
 "panels": [
  {
   "title": "Информация о системе",
   "type": "stat",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_cpu_info",
     "legendFormat": "{{model_name}} (Cores: {{core}}, Family: {{family}})"
    }
   ]
  },
  {
   "title": "Общая утилизация CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "Загрузка CPU"
    }
   ]
  },
  {
   "title": "Потребление ресурсов CPU по режимам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (mode) (rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Частота ядер процессора",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "GHz" } },
   "targets": [
    {
     "expr": "node_cpu_frequency_hertz / 1000000000",
     "legendFormat": "Ядро {{cpu}}"
    }
   ]
  }
 ]
}